namespace DeskBook.Infrastructure.Resource;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class ResponseMessage
{

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal ResponseMessage()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeskBook.Infrastructure.Resource.ResponseMessage", typeof(EmailDetail).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
        get
        {
            return resourceCulture;
        }
        set
        {
            resourceCulture = value;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Deskbook Application - Seat Request Rejection.
    /// </summary>
    public static string? InternalServerError
    {
        get
        {
            return ResourceManager.GetString("InternalServerError", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to We hope this email finds you well. We have received your application and regret to inform you that your seat request has been rejected by the seat owner.
    /// 
    /// We understand that this may be disappointing news, and we want to assure you that our decision was not made lightly.
    /// 
    /// Thank you for your application, and we wish you the best of luck in your future endeavors..
    /// </summary>
    public static string? RegistrationSuccessful
    {
        get
        {
            return ResourceManager.GetString("RegistrationSuccessful", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Approval of Your Office Seat in the Deskbook Application System.
    /// </summary>
    public static string? BadRequest
    {
        get
        {
            return ResourceManager.GetString("BadRequest", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up
    public static string? EmailExist
    {
        get
        {
            return ResourceManager.GetString("EmailExist", resourceCulture);
        }
    }

    public static string? RegistrattionFailed
    {
        get
        {
            return ResourceManager.GetString("RegistrattionFailed", resourceCulture);
        }
    }

    public static string? MinCharacter
    {
        get
        {
            return ResourceManager.GetString("MinCharacter", resourceCulture);
        }
    }

    public static string? EmployeeIdNotFound
    {
        get
        {
            return ResourceManager.GetString("EmployeeIdNotFound", resourceCulture);
        }
    }

    public static string? SavedSuccessfully
    {
        get
        {
            return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
        }
    }

    public static string? RequestIdnotFound
    {
        get
        {
            return ResourceManager.GetString("RequestIdnotFound", resourceCulture);
        }
    }

    public static string? SuccessfulChanges
    {
        get
        {
            return ResourceManager.GetString("SuccessfulChanges", resourceCulture);
        }
    }


    public static string? NoDataFound
    {
        get
        {
            return ResourceManager.GetString("NoDataFound", resourceCulture);
        }
    }

    public static string? MaximumLimit
    {
        get
        {
            return ResourceManager.GetString("MaximumLimit", resourceCulture);
        }
    }

    public static string? ConsecutiveOrder
    {
        get
        {
            return ResourceManager.GetString("ConsecutiveOrder", resourceCulture);
        }
    }

    public static string? SeatAdded
    {
        get
        {
            return ResourceManager.GetString("SeatAdded", resourceCulture);
        }
    }

    public static string? StatusNotChanged
    {
        get
        {
            return ResourceManager.GetString("StatusNotChanged", resourceCulture);
        }
    }

    public static string? UnassignStatus
    {
        get
        {
            return ResourceManager.GetString("UnassignStatus", resourceCulture);
        }
    }

    public static string? UnavailableStatus
    {
        get
        {
            return ResourceManager.GetString("UnavailableStatus", resourceCulture);
        }
    }

    public static string? ErrorOccured
    {
        get
        {
            return ResourceManager.GetString("ErrorOccured", resourceCulture);
        }
    }
   
}

